### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

spring.datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hifish_service?autoReconnect=true&useSSL=false
    username: root
    password: root


server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: hifish-service
  version: 0.1
  description: hi fish app server
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

hotel.service:
  name: 'default profile:'
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    test-on-borrow: true
    validation-query: select 1


###wechat##
wechat:
  token: hifish
  appid: wx690cea67271973b8
  appsecret: 375173429b9f4a502dc849119c37460b
  token.type: client_credential
  token.url: https://api.weixin.qq.com/cgi-bin/token
  cgi:
    userinfo:
      url: https://api.weixin.qq.com/cgi-bin/user/info
  oauth_token:
    url: https://api.weixin.qq.com/sns/oauth2/access_token
    type: authorization_code
  sns:
    userinfo:
      url: https://api.weixin.qq.com/sns/userinfo
  jsapi_ticket:
    type: jsapi
    url: https://api.weixin.qq.com/cgi-bin/ticket/getticket

# RabbitMQ
mqtt:
  topic: deviceServerTopic
  testTopic: testTopic
  deviceWillTopic: device-will
  qos: 0
  broker: tcp://106.185.35.79:1883
  userName:  /liji:liji_host
  password: liji_host
